# Generated by Django 5.2 on 2025-05-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautysalon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
