@startuml class

' !pragma layout smetana
' left to right direction

' skinparam linetype polyline
' skinparam linetype ortho
' skinparam groupInheritance 2


enum PaymentMethod {
  Cash
  CreditCard
  DebitCard
}

enum AppointmentStatus {
  Booked
  Confirmed
  Cancelled
  Completed
}

enum ExpertiseLevel {
  Junior
  Intermediate
  Senior
}

class Client {
  string Name
}

class Image {
  string Url
}

class Person {
  string Name
  string Surname
  string PhoneNumber
  string LegalId
  string Address
}

class Genre {
  string Name
}

class Client {
  bool IsLoyal
}

Person <|-- Client

class User {
  string Name
  string Password
}

class Role {
  string Name
}

class Review {
  float Rating
  string Comment
}

Review "1..*" -- "1" Service

class Promotion {

}

Promotion "1..*" -- "1" Service

class Category

Category "1..*" -- "1..*" Service

class CategoryService

(Category, Service) .. CategoryService

class OpeningHours {
  DateOnly Date
  TimeOnly OpenTime
  TimeOnly CloseTime
}

class Appointment {
  DateTime Date
  string Note
}

Appointment "1..*" -- "1..*" Service

class ServiceDetail

(Appointment, Service) .. ServiceDetail

class Notification {

}

class BeautySalon

class Branch {
  string Address
  string PhoneNumber
}

class Employee

class SocialNetwork

class FranchisePayment

class EmployeeOperationHours


Client "1" -- "0..*" Appointment
Genre "1" -- "1..*" Person
Person "1" -- "1" User
User "1..*" -- "1" Role
Person <|-- Employee
Branch "1" -- "1..*" Employee
Branch "1" -- "1..*" OpeningHours
Service "1..*" -- "1" BeautySalon
BeautySalon "1" -- "1..*" SocialNetwork
BeautySalon "1" -- "1..*" FranchisePayment
FranchisePayment -- PaymentMethod

class Bill {
  DateOnly Date
  string Code
  string Name
  string Surname
}

FranchisePayment --|> Bill
BeautySalon "1" -- "1..*" Branch
Employee "1"-- "1..*" EmployeeOperationHours

class Specialty {
  string Name
}

class Training {

}

Employee "1..*" -- "1..*" Specialty
(Employee, Specialty) .. Training

Appointment "1" -- "1..*" Notification
Appointment "1" -- "1..*" Image

hide methods


@enduml