# Generated by Django 5.2 on 2025-06-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('salons', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='requested', max_length=50)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('mobile_payment', 'Mobile Payment'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=50)),
                ('note', models.TextField(blank=True)),
                ('beauty_salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.beautysalon')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salons.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customerprofile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employeeprofile')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
        ),
    ]
