# Generated by Django 5.2 on 2025-05-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
