# Generated by Django 5.2 on 2025-06-18 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautySalon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_uri', models.URLField(blank=True)),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo_uri', models.URLField(blank=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='salons.beautysalon')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='salons.branch')),
            ],
            options={
                'verbose_name_plural': 'Opening Hours',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='salons.beautysalon')),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='beautysalon',
            index=models.Index(fields=['-created_at'], name='salons_beau_created_6f0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='beautysalon',
            index=models.Index(fields=['-updated_at'], name='salons_beau_updated_7673bf_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['-created_at'], name='salons_bran_created_65c9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['-updated_at'], name='salons_bran_updated_ca5344_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together={('branch', 'day')},
        ),
        migrations.AddIndex(
            model_name='socialnetwork',
            index=models.Index(fields=['-created_at'], name='salons_soci_created_004e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='socialnetwork',
            index=models.Index(fields=['-updated_at'], name='salons_soci_updated_f9ac07_idx'),
        ),
    ]
