name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        run: uv pip install -r requirements.txt || uv pip install .

      - name: Ensure Django 5.2 is installed
        run: uv pip install django==5.2

      - name: Run migrations
        run: uv python manage.py migrate

      - name: Run tests
        run: uv python manage.py test

      - name: Lint with ruff
        run: |
          uv pip install ruff
          uv python -m ruff .
